services:
  settlesentry:
    image: ghcr.io/kayvanshah1/settlesentry-payment-collection-agent:latest
    pull_policy: missing
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      LOG_CONSOLE_ENABLED: "false"
    volumes:
      - ./var:/app/var
      - ./logs:/app/logs
    command: ["chat", "--mode", "deterministic-workflow"]

  settlesentry-autonomous:
    image: ghcr.io/kayvanshah1/settlesentry-payment-collection-agent:latest
    pull_policy: missing
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      LOG_CONSOLE_ENABLED: "false"
      OPENROUTER_ENABLED: "true"
    volumes:
      - ./var:/app/var
      - ./logs:/app/logs
    command: ["chat", "--mode", "llm-autonomous-agent"]
    profiles:
      - llm
